spring:
  datasource:
    url: jdbc:mysql://localhost:3306/activiti?useSSL=true&characterEncoding=UTF-8&serverTimezone=UTC&nullCatalogMeansCurrent=true
    username: root
    password: cuoai1995
    driver-class-name: com.mysql.jdbc.Driver
  activiti:
    check-process-definitions: false
    database-schema-update: true